sudo: false
language: node_js
node_js:
  - lts/* # use nodejs v10 LTS
cache: 
  directories:
    - node_modules
install:
  - npm install hexo-cli -g
  - npm install

branches:
  only:
    - source # build master branch only
script:
  - hexo generate # generate static files
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN
#   keep-history: true
#   on:
#     repo: https://github.com/Haoxiaoling/Haoxiaoling.github.io.git
#     branches:
#       only:
#         - master
#   local-dir: public
after_script:
  - cd ./public
  - git init
  - git config user.name "travis"
  - git config user.email "travis@ci.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
