sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $9222f9a04216004070778e1e2f47c6c4f644000a
  keep-history: true
  on:
    branch: master
  local-dir: public
after_success:
  - git config --global user.name "travis"
  - git config --global user.email "travis@ci.com"
  - hexo d
